# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239ff8cfda17402d89fe2bab834a242c24a69ed95b70890f157e075444d1b52748d84e5c6ddcbbc7bb5e6a54374e83db614ad6561fc26877d96694435f974ae4

test:
  secret_key_base: 669f608dfc19d9b8fd030e83e8a28a9bf2faedb75f0680f1c7370314e8e539b4980524be47be24b20436b6fbd6a867daef021ec024a4622ce6bfe36231ce63ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
